local cache = require("local_llm.cache")
local eq = assert.are.same

describe("cache", function()
  it("stores and retrieves values", function()
    local c = cache.new(4)
    c:set("k1", { "a" })
    eq({ "a" }, c:get("k1"))
  end)
  it("evicts least-recently-used entries when full", function()
    local c = cache.new(2)
    c:set("a", 1)
    c:set("b", 2)
    c:get("a")
    c:set("c", 3)
    assert.is_nil(c:get("b"))
    eq(1, c:get("a"))
  end)
end)
